### ISSUE TITLE
Unbound value hash_fold_int

### ISSUE THREAD

**Issue by mimoo** [janestreet/ppx_hash#3]
I am trying to derive hash on a record that relies on another type `t = int`. If I don't derive anything on that other type I get:

```
File "narwhall.ml", line 98, characters 13-29:
98 |     source : Ed25519.Pubkey.t;
                  ^^^^^^^^^^^^^^^^
Error: Unbound value Ed25519.Pubkey.hash_fold_t
```

So I derived it:

```
module Ed25519 = struct
  module Pubkey = struct
    type t = int [@@deriving hash, eq]
```

but then I get:

```
➜  narwhall git:(main) ✗ esy b dune runtest
File "narwhall.ml", line 59, characters 13-16:
59 |     type t = int [@@deriving hash, eq]
                  ^^^
Error: Unbound value hash_fold_int
```

**Comment by aalekseyev** [comment]
For deriving on primitive types to work you need to open a library that provides the corresponding definitions.
I know `open Base` is sufficient, but there may be something you can do specifically for `@@deriving hash`. Maybe `open  Ppx_hash_lib.Std.Hash.Builtin`, but I would actually still recommend `open Base` instead.
